export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';

export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_RECIPE_REQUEST = 'FETCH_RECIPE_REQUEST';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';